###
POST http://localhost:5000/register
Content-Type: application/json

{
    "username":"keka",
    "name":"uday",
    "password" : "keka123"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "pavan",
    "password" : "pavan123"
}

###
GET  http://localhost:5000/products?sort_by=ASC&category=&title_search=&rating=4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdmFuIiwiaWF0IjoxNjg0ODI1MTI1fQ.1qw_io6YsVkuplW2YBr5c9GEaD4OpPMihVuzSeVcKso


###

GET http://localhost:5000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdmFuIiwiaWF0IjoxNjg0ODI1MTI1fQ.1qw_io6YsVkuplW2YBr5c9GEaD4OpPMihVuzSeVcKso




###
GET http://localhost:5000/similar-products/39
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdmFuIiwiaWF0IjoxNjg1MzgxMzEyfQ.sVaeBZi3e8eiIEHLdZvK9fTTti3nyhDRFMCVQc94Fuc


###
GET http://localhost:5000/other-products/39
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdmFuIiwiaWF0IjoxNjg1MzgxMzEyfQ.sVaeBZi3e8eiIEHLdZvK9fTTti3nyhDRFMCVQc94Fuc


###
GET http://localhost:5000/prime-deals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdmFuIiwiaWF0IjoxNjg1MzgxMzEyfQ.sVaeBZi3e8eiIEHLdZvK9fTTti3nyhDRFMCVQc94Fuc

###
POST http://localhost:5000/admin/addproduct
Content-Type: application/json

{  
       "title": "Tea Kettle Pot",
        "brand": "Indian Art Villa",
        "price": 1685,
        "id": 26,
        "image_url": "https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-copper-kettle.png",
        "rating": "3.8",
        "category" : "APPLIANCES"
}